---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара и в каталоге должно быть выведено название, рейтинг, цена со скидкой и без нее.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице корзины пользователь должен иметь возможность удалить товар из корзины и продолжить выбирать товары в каталоге
  - Каталог товаров должен выводиться на экран постранично
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
  - Корзина должна храниться в сессии браузера
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implisit:
  - Пользователь должен оставить свои контактные данные (имя и телефон или e-mail)
    для связи с ним после оформления заказа
  - Полсе оформления заказа, заказанные товары должны удалиться из корзины
  - Клик по кнопке "Магазин" должен вести на главную страницу
  - Клик по логотипу "Hexlet Store"должен вести на главную страницу
  - Пользователь не должен иметь возможность редактировать описание товара
