---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implisit:
  - Пользователь должен оставить свои контактные данные (имя и телефон или e-mail)
    для связи с ним после оформления заказа
  - Полсе оформления заказа, заказанные товары должны удалиться из корзины
  - Клик по кнопке "Магазин" должен вести на главную страницу
  - Клик по логотипу "Hexlet Store"должен вести на главную страницу
  - Пользователь не должен иметь возможность редактировать описание товара
